export const SET_LANGUAGE_TABLE = "SET_LANGUAGE_TABLE";
export const SET_LANGUAGE_TABLE_DATA = "SET_LANGUAGE_TABLE_DATA";
export const GENERATE_STRING_VALUE_SUCCESS = "GENERATE_STRING_VALUE_SUCCESS";
export const GENERATE_STRING_VALUE_ERROR = "GENERATE_STRING_VALUE_ERROR";
